version: '3'

services:
  db:
    build: mysql/
    restart: always
    env_file: mysql/mysql.env
    image: cross_browser_mysql

  server:
    build: server/
    env_file: mysql/mysql.env
    image: cross_browser_server
    ports:
      - "80:80"
