version: '3'

services:
  db:
    build: mysql/
    restart: always
    env_file: mysql/mysql.env
    image: cross_browser_mysql
    volumes:
      - db_volume:/var/lib/mysql

  server:
    build: server/
    env_file: mysql/mysql.env
    image: cross_browser_server
    ports:
      - "80:80"

volumes:
  db_volume: